sudo: required

language: node_js

before_install:
  - npm i -g npm@6

node_js:
  - "8"
  - "12"

before_script:
  - npm run setup

script:
  - npm run lint:nofix
  - npm run test

jobs:
  include:
    - stage: bench
      addons:
        apt:
          sources: google-chrome
          packages: google-chrome-stable
      skip_cleanup: true
      # https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-services-xvfb
      services:
        - xvfb
      script: npm run bench
    - stage: npm release
      if: tag IS present
      node_js: "8"
      script: npm run build
      before_deploy:
        - NPM_DEPLOY_TARGET=`node -e 'console.log((/deploy:\ ([a-z_-\d]+)/.exec(process.env.TRAVIS_COMMIT_MESSAGE)||[,""])[1])'`
        - cd "packages/$NPM_DEPLOY_TARGET"
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          tags: true
          branch: chore-ci-test
        tag: latest

stages:
  - test # default stage
  - name: bench
    # require the branch name to be master (note for PRs this is the base branch name)
    if: (branch = master AND type != pull_request) OR branch =~ ^bench
